version: '3'
services:
  receiver-service:
    build: ./receiver
    environment:
      - NODE_ENV=development
    ports:
      - "6000:6000"
    volumes:
      - ./receiver/src:/receiver/src

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - receiver-service
    volumes:
      - ./config:/etc/nginx

